#!/usr/bin/env python3
"""Create a repeatable Palmier Pro production project folder."""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import re
from pathlib import Path


DIRS = [
    "brief",
    "script",
    "assets/user",
    "assets/generated/images",
    "assets/generated/video",
    "assets/generated/audio",
    "assets/thumbnails",
    "edit",
    "exports/longform",
    "exports/shorts",
    "publish",
    "review",
]


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value[:72] or "untitled-video"


def write_if_missing(path: Path, content: str) -> None:
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def create_project(idea: str, output: Path, channel: str | None) -> Path:
    today = dt.date.today().isoformat()
    project_dir = output / f"{today}-{slugify(idea)}"
    project_dir.mkdir(parents=True, exist_ok=True)

    for dirname in DIRS:
        (project_dir / dirname).mkdir(parents=True, exist_ok=True)

    manifest = {
        "idea": idea,
        "channel": channel or "",
        "created": today,
        "status": "intake",
        "folders": DIRS,
        "notes": "Generated by the palmier-pro-production Codex skill.",
    }
    manifest_path = project_dir / "manifest.json"
    if not manifest_path.exists():
        manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    ledger_path = project_dir / "asset-ledger.csv"
    if not ledger_path.exists():
        with ledger_path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(
                [
                    "filename",
                    "folder",
                    "type",
                    "source",
                    "rights",
                    "prompt_or_origin",
                    "palmier_status",
                    "notes",
                ]
            )

    write_if_missing(
        project_dir / "brief" / "creative-brief.md",
        f"""# Creative Brief

Working title:

Idea:
{idea}

Channel:
{channel or ""}

Viewer promise:

Target viewer:

Format and runtime:

Hook:

Payoff:

Assets needed:

Risks and approvals:

Success metric:
""",
    )
    write_if_missing(project_dir / "script" / "longform-script.md", "# Long-Form Script\n\n")
    write_if_missing(project_dir / "script" / "shorts-scripts.md", "# Shorts Scripts\n\n")
    write_if_missing(project_dir / "edit" / "edit-decision-list.md", "# Edit Decision List\n\n")
    write_if_missing(project_dir / "edit" / "palmier-handoff.md", "# Palmier Handoff\n\n")
    write_if_missing(project_dir / "publish" / "upload-package.md", "# Upload Package\n\n")
    write_if_missing(project_dir / "review" / "watchdown-notes.md", "# Watchdown Notes\n\n")

    return project_dir


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("idea", help="Short description of the video idea.")
    parser.add_argument("--output", default="./palmier-projects", help="Parent folder for projects.")
    parser.add_argument("--channel", default="", help="Optional channel or personal brand name.")
    args = parser.parse_args()

    project_dir = create_project(args.idea, Path(args.output).expanduser().resolve(), args.channel)
    print(project_dir)


if __name__ == "__main__":
    main()
